# Generated by Django 5.2.7 on 2025-11-05 08:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for this banner', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is currently active')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the banner (JPG, PNG, GIF)', max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video for the banner (MP4, WebM)', max_length=255, null=True, verbose_name='video')),
                ('link_url', models.URLField(blank=True, help_text='URL to redirect when banner is clicked')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('locations', models.JSONField(default=list, help_text='List of locations where this banner should appear')),
                ('size', models.CharField(choices=[('small', 'Small (120px - Sidebar)'), ('medium', 'Medium (150px - Between sections)'), ('large', 'Large (200px - Major sections)'), ('card', 'Card (250px - Grid layouts)'), ('row', 'Row (100px - Inside lists)')], default='medium', help_text='Size variant for the banner', max_length=20)),
                ('impressions', models.IntegerField(default=0, help_text='Number of times banner was displayed')),
                ('clicks', models.IntegerField(default=0, help_text='Number of times banner was clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Banner',
                'verbose_name_plural': 'Ad Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
