# Generated by Django 5.2.7 on 2025-10-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reportreason_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
