# Generated by Django 5.2.7 on 2025-11-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
