# Generated by Django 5.2.7 on 2025-11-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_poll_polloption_topicimage_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
