# Generated by Django 5.2.7 on 2025-11-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_alter_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
