# Generated by Django 5.2.7 on 2025-11-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_categoryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
