# Generated by Django 5.2.7 on 2025-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_userprofile_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_image',
        ),
    ]
