# Generated by Django 5.2.7 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
