# Generated by Django 5.2.7 on 2025-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_userprofile_facebook_url_userprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
