# Generated by Django 5.2.7 on 2025-11-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO. If empty, tags will be used or title will be split into words.', max_length=300),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Optional SEO description. If empty, an excerpt from content will be used.', max_length=300),
        ),
        migrations.AddField(
            model_name='topic',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Optional SEO title. If empty, the topic title will be used.', max_length=255),
        ),
    ]
