# Generated by Django 5.2.7 on 2025-11-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_topic_keywords_topic_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='meta_title',
        ),
    ]
