# Generated by Django 5.2.7 on 2025-11-06 10:09

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0025_remove_topic_keywords_remove_topic_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='forum.reply')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
