# Generated by Django 5.2.7 on 2025-11-06 11:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0026_replyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='CarForum - Automotive Discussion Community', max_length=200)),
                ('site_description', models.TextField(default='Join CarForum to discuss cars, share experiences, and connect with automotive enthusiasts.')),
                ('site_keywords', models.TextField(default='car forum, automotive discussion, car community, vehicle talk', help_text='Comma-separated keywords for SEO')),
                ('google_verification', models.CharField(blank=True, help_text='Google Search Console verification code', max_length=100)),
                ('yandex_verification', models.CharField(blank=True, help_text='Yandex Webmaster verification code', max_length=100)),
                ('bing_verification', models.CharField(blank=True, help_text='Bing Webmaster verification code', max_length=100)),
                ('og_image', cloudinary.models.CloudinaryField(blank=True, help_text='Default Open Graph image for social sharing', max_length=255, null=True, verbose_name='image')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter/X handle (without @)', max_length=50)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('site_url', models.URLField(default='http://localhost:3000', help_text='Main site URL (for canonical URLs and sitemap)')),
                ('api_url', models.URLField(default='http://localhost:8000', help_text='API base URL')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('maintenance_message', models.TextField(default='We are currently performing maintenance. Please check back soon.', help_text='Message to display during maintenance')),
                ('registration_enabled', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('registration_message', models.TextField(blank=True, help_text='Optional message to display when registration is disabled')),
                ('topics_per_page', models.IntegerField(default=20, help_text='Number of topics per page')),
                ('replies_per_page', models.IntegerField(default=10, help_text='Number of replies per page')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='Google Tag Manager ID (e.g., GTM-XXXXXXX)', max_length=50)),
                ('contact_email', models.EmailField(default='support@carforum.com', help_text='Contact email for inquiries', max_length=254)),
                ('admin_email', models.EmailField(default='admin@carforum.com', help_text='Admin email for notifications', max_length=254)),
                ('show_announcement', models.BooleanField(default=False, help_text='Show announcement banner')),
                ('announcement_text', models.TextField(blank=True, help_text='Announcement banner text')),
                ('announcement_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], default='info', help_text='Announcement banner style', max_length=20)),
                ('announcement_link', models.URLField(blank=True, help_text='Optional link for the announcement')),
                ('announcement_link_text', models.CharField(blank=True, help_text='Text for the announcement link', max_length=100)),
                ('auto_hide_reported_replies', models.IntegerField(default=5, help_text='Automatically hide replies after this many reports (0 to disable)')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Require email verification for new users')),
                ('allow_topic_images', models.BooleanField(default=True, help_text='Allow images in topics')),
                ('allow_polls', models.BooleanField(default=True, help_text='Allow polls in topics')),
                ('max_images_per_topic', models.IntegerField(default=5, help_text='Maximum images per topic')),
                ('max_poll_options', models.IntegerField(default=10, help_text='Maximum poll options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
