# Generated by Django 5.2.7 on 2026-01-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0027_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Unique key to identify this translation (e.g., 'header.search_placeholder')", max_length=200, unique=True)),
                ('text_ka', models.TextField(help_text='Text in Georgian language', verbose_name='Georgian Text')),
                ('text_en', models.TextField(help_text='Text in English language', verbose_name='English Text')),
                ('description', models.TextField(blank=True, help_text='Description of where this text is used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this translation is active')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['key'],
            },
        ),
    ]
