# Generated by Django 5.2.7 on 2025-11-03 11:29

from django.db import migrations


def create_topic_likes_badges(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    
    # Single Topic Milestone Badges
    Badge.objects.get_or_create(
        name='Liked Post',
        defaults={
            'description': 'Receive 10 likes on a single topic',
            'icon': '👍',
            'category': 'social',
            'requirement_count': 10,
            'xp_reward': 50,
            'is_active': True
        }
    )
    
    Badge.objects.get_or_create(
        name='Popular Post',
        defaults={
            'description': 'Receive 50 likes on a single topic',
            'icon': '🔥',
            'category': 'social',
            'requirement_count': 50,
            'xp_reward': 150,
            'is_active': True
        }
    )
    
    Badge.objects.get_or_create(
        name='Viral Post',
        defaults={
            'description': 'Receive 100 likes on a single topic',
            'icon': '🚀',
            'category': 'social',
            'requirement_count': 100,
            'xp_reward': 300,
            'is_active': True
        }
    )
    
    # Total Likes Milestone Badges
    Badge.objects.get_or_create(
        name='Well Liked',
        defaults={
            'description': 'Receive a total of 100 likes across all your topics',
            'icon': '💙',
            'category': 'social',
            'requirement_count': 100,
            'xp_reward': 100,
            'is_active': True
        }
    )
    
    Badge.objects.get_or_create(
        name='Community Favorite',
        defaults={
            'description': 'Receive a total of 500 likes across all your topics',
            'icon': '⭐',
            'category': 'social',
            'requirement_count': 500,
            'xp_reward': 250,
            'is_active': True
        }
    )
    
    Badge.objects.get_or_create(
        name='Influencer',
        defaults={
            'description': 'Receive a total of 1000 likes across all your topics',
            'icon': '👑',
            'category': 'social',
            'requirement_count': 1000,
            'xp_reward': 500,
            'is_active': True
        }
    )
    
    Badge.objects.get_or_create(
        name='Superstar',
        defaults={
            'description': 'Receive a total of 2000 likes across all your topics',
            'icon': '🌟',
            'category': 'social',
            'requirement_count': 2000,
            'xp_reward': 1000,
            'is_active': True
        }
    )


def reverse_badges(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    badge_names = [
        'Liked Post', 'Popular Post', 'Viral Post',
        'Well Liked', 'Community Favorite', 'Influencer', 'Superstar'
    ]
    Badge.objects.filter(name__in=badge_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_topic_likes_badges, reverse_badges),
    ]
