# Generated by Django 5.2.7 on 2025-11-03 11:34

from django.db import migrations


def create_moderator_friend_badge(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    
    Badge.objects.get_or_create(
        name='Moderator Friend',
        defaults={
            'description': 'Report 10 inappropriate posts',
            'icon': '🛡️',
            'category': 'helpful',
            'requirement_count': 10,
            'xp_reward': 100,
            'is_active': True
        }
    )


def reverse_badge(apps, schema_editor):
    Badge = apps.get_model('gamification', 'Badge')
    Badge.objects.filter(name='Moderator Friend').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_add_topic_likes_badges'),
    ]

    operations = [
        migrations.RunPython(create_moderator_friend_badge, reverse_badge),
    ]
