# Generated by Django 5.2.7 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_add_moderator_friend_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('xp_required', models.IntegerField(help_text='Total XP required to reach this level')),
                ('icon', models.CharField(blank=True, default='⭐', max_length=10)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
    ]
