# Generated by Django 5.2.7 on 2025-11-03 12:20

from django.db import migrations


def create_default_levels(apps, schema_editor):
    Level = apps.get_model('gamification', 'Level')
    
    # Define default levels with progressive XP requirements
    default_levels = [
        (1, 'Newbie', 0, '🌱', '#94a3b8'),
        (2, 'Beginner', 500, '🔰', '#3b82f6'),
        (3, 'Member', 1200, '⚡', '#06b6d4'),
        (4, 'Active Member', 2100, '💫', '#8b5cf6'),
        (5, 'Contributor', 3300, '✨', '#6366f1'),
        (6, 'Regular', 4800, '🌟', '#a855f7'),
        (7, 'Expert', 6800, '💎', '#ec4899'),
        (8, 'Veteran', 9500, '👑', '#f59e0b'),
        (9, 'Master', 13000, '🏆', '#f97316'),
        (10, 'Legend', 18000, '⚜️', '#ef4444'),
        (11, 'Elite', 25000, '🔱', '#dc2626'),
        (12, 'Champion', 35000, '🎖️', '#991b1b'),
        (13, 'Hero', 50000, '🦸', '#7c2d12'),
        (14, 'Mythic', 70000, '🌌', '#581c87'),
        (15, 'Legendary', 100000, '🔥', '#fbbf24'),
    ]
    
    for level_number, name, xp_required, icon, color in default_levels:
        Level.objects.get_or_create(
            level_number=level_number,
            defaults={
                'name': name,
                'xp_required': xp_required,
                'icon': icon,
                'color': color,
                'is_active': True
            }
        )


def reverse_levels(apps, schema_editor):
    Level = apps.get_model('gamification', 'Level')
    Level.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_level'),
    ]

    operations = [
        migrations.RunPython(create_default_levels, reverse_levels),
    ]
