# Generated by Django 5.2.7 on 2025-11-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_populate_default_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlevel',
            name='level_name',
        ),
    ]
