# Generated by Django 5.2.7 on 2025-11-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_remove_userlevel_level_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom level image (optional, falls back to icon)', null=True, upload_to='level_images/'),
        ),
    ]
