# Generated by Django 5.2.7 on 2025-11-03 14:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_level_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Custom level image (optional, falls back to icon)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
